version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=socialRunCommunity;Username=dmitry;Password=Corvus404
    volumes:
      - ./certs:/etc/ssl/certs
      - ./certs:/etc/ssl/private
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: socialRunCommunity
      POSTGRES_USER: dmitry
      POSTGRES_PASSWORD: Corvus404
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
