version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"       # HTTP
      - "443:443"     # HTTPS
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - /etc/ssl:/etc/ssl:ro
    depends_on:
      - database
      
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialRunCommunity
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
