version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000" # Только HTTP, Nginx будет работать через 443
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - database
    networks:
      - backend

  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialRunCommunity
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl:/etc/ssl:ro
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata:
